language: node_js
node_js:
- 10
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
install:
- npm ci
script:
- update-locale LANG=fr_FR.UTF-8
- update-locale LANGUAGE=fr
- locale
- npm run cy:run:record -- --key $RECORD_KEY
